# Add at the top, before other settings
logtime: true
log_file: "/dev/stdout"
debug: true
trace: false

host: 0.0.0.0
port: 4222
http_port: 8222
server_name: node-three

websocket {
    port: 9222
    no_tls: true
    compression: true
}

jetstream {
    store_dir: /data/nats/node-three
    max_mem: 1G
    max_file: 10G
    domain: trade
}

cluster {
  name: local-cluster
  port: 6222
  routes: [
    nats://nats-node-one:6222
    nats://nats-node-two:6222
  ]
}

accounts {
  AUTH {
    jetstream: enable
    users: [
      { user: auth, password: auth }
    ]
    exports: [
      { stream: "user.>" }
      { stream: "community.>" }
      { stream: "guilds.>" }
    ]
    imports: [
      { stream: { account: APP, subject: "client.presence.>" } }
    ]
  }
  APP {
    jetstream: enable
    exports: [
      { stream: "client.presence.>" }
    ]
    imports: [
      { stream: { account: AUTH, subject: "user.>" } }
      { stream: { account: AUTH, subject: "community.>" } }
      { stream: { account: AUTH, subject: "guilds.>" } }
    ]
  }
  SYS {}
}

authorization {
  auth_callout {
    issuer: AA4BWGINSTZDZUEIV7Z5YK3L3KPKLAFBOS2SGKL4XJEX6MSY75FSIUAT
    users: [ auth ]
    account: AUTH
  }
}

system_account: SYS